version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/resumate-deploy/  #프로젝트 이름
    overwrite: yes

permissions:
  - object: /home/ubuntu/resumate-deploy/
    pattern: "**"
    owner: root
    group: root

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 120
      runas: root
    - location: scripts/health_check.sh
      timeout: 60
      runas: root